### ISSUE TITLE
Icons: check icon manifest files

### ISSUE THREAD

**Issue by StuckiSimon** [Goldinteractive/gold-features#2]
Currently icons do not check the returned fragment for validity.
In case of 404 or similar issue the error will therefore be strange since it failed to parse json.

There should be a check ahead of parsing the returned data.

https://github.com/Goldinteractive/gold-features/blob/master/packages/icons/src/index.js#L58

**Comment by MitchGabriel** [comment]
@StuckiSimon any progress?

**Comment by StuckiSimon** [comment]
@MitchGabriel No, this is currently not on my agenda. Feel free to discard the issue or solve it ✌
