### ISSUE TITLE
TouchHover: createEvent fails in Safari

### ISSUE THREAD

**Issue by sir-marc** [Goldinteractive/gold-features#4]
TouchHover feature throws error in safari 12 because `document.createEvent` is not defined.

https://github.com/Goldinteractive/gold-features/blob/e615fb0564cb3a578e12680225c0f35b13f9a882/packages/touch-hover/src/index.js#L62

**Comment by StuckiSimon** [comment]
This feature is supported in Safari 12.1 - which is the last supported version of Safari.
Will therefore close this issue based on dropped browser support.
